name: flutter_pdf_renderer
description: Render pages of a PDF file as images
version: 0.0.1
author: Cosmic Effect

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.cosmiceffect.pdf_renderer
        pluginClass: PdfRendererPlugin
